version: '3.1'

volumes:
  data:

services:
  postgres:
    container_name: pg_phoenix
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=einfach
      - POSTGRES_USER=postgres      
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql